@startuml
start

repeat
  split
    :Choose Project;
    :Chose a Project from the list;
'  split again
'    :Delete Project;
'    :Chose a Project from the list;
'    :confirm>
  split again
    :Create new Project;
    split
      :Offline Mode;
    split again
      :Login user;
      split
        :Login with a web browser;
        'https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#device-flow
      split again
        :Paste an authentication token;
        'PAT Token
      split again
        :Login SSH;
        'list files to select in ~/.ssh
      end split
    end split
    :- enter project name
      responsive feedback if repo exists
    - (creating local repo (if logged in also github));
  split again
    :Open remote Project;
    - enter project name
    - clone project if not present
  split again
    :exit;
    end
  end split

  repeat
    :Open Project view (offline/online mode);
    split
      :New Image;
      :Select Image and show preview graph;
      :Select year;
      if (year has contributions) then (yes)
        :Inform user and wait for extra confirmations>
      endif
      :Generating commits...>
      if (push?) then (yes)
        :Pushing to remote <remote>;
      endif
    split again
      :View Images;
      :print a list of images;
      :Show github graph of that image;
      :confirm viewing>
    split again
      :Delete Image;
      :Select image to delete;
      :confirm deletion>
      :removing commits...;
      if (push?) then (yes)
        :Pushing to remote <remote> with force;
      endif
    split again
      :Back to home;
    split again
      :Delete project|
      :confirm deletion>
      if (also delete GitHub Repo?) then (yes)
        :delete github repo;
        :confirm deletion>
      endif
      :deleted repo, go back to home;
    end split
    :done confirmation>
  repeat while (in project?)
repeat while (true)

@enduml
